language: python
cache: pip
install:
  - pip install awscli
script:
  - echo "let's GO, DAWG!"
before_deploy:
  - echo "this site was updated by travis with build id $TRAVIS_BUILD_ID" > $TRAVIS_BUILD_DIR/build.txt
deploy:
  - export AWS_ACCESS_KEY=$AWS_ACCESS_KEY
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  - aws s3 cp $TRAVIS_BUILD_DIR/ s3://casale.io/
after_deploy:
  - aws cloudfront create-invalidation --distribution-id E16QZCXFF2GO4 --paths "/*"
