language: python
cache: pip
install:
  - pip install awscli
before_deploy:
  - echo "this site was updated by travis with build id $TRAVIS_BUILD_ID" > $TRAVIS_BUILD_DIR/build.txt
script:
  - echo "LET'S GO, DAWG!"
  - export AWS_ACCESS_KEY=$AWS_ACCESS_KEY
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  - aws configure
  - aws s3 cp $TRAVIS_BUILD_DIR/ s3://casale.io/ --recursive
  - aws cloudfront create-invalidation --distribution-id E16QZCXFF2GO4 --paths "/*"
